version: "3.8"
#test
services:
  minio_db:
    image: docker.io/bitnami/minio:2025
    container_name: mm_minio_db
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=object-models
    volumes:
      - 'minio_data:/bitnami/minio/data'
    networks:
      - mm-net

  museum_db_pg_sql:
    image: postgres:16
    container_name: mm_postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=museum
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mm-net

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    network_mode: host

volumes:
  minio_data:
  minio_bitnami_data:
  minio_certs:
  pg_data:

networks:
  mm-net:
    name: mm-net
    driver: bridge
